version: '3'
services:
  tedge:
    build:
      dockerfile: images/Dockerfile
    privileged: true
    volumes:
      - /var/run/docker.sock:${DOCKER_SOCKET:-/var/run/docker.sock}:rw
      - certs:/etc/tedge/device-certs
    tmpfs:
      - /run
      - /tmp
    networks:
      - tedge

volumes:
  certs:

networks:
  # Fix the name of the container so that single container deployments can be connected
  # to a well known network name
  tedge:
    name: tedge
    # external: true
