name: release
permissions:
  contents: write
on:
  push:
    tags:
      - "*"
  workflow_dispatch:
jobs:
  release:
    name: Package and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.17.0'
      - run: go install github.com/goreleaser/nfpm/v2/cmd/nfpm@latest
        name: Install dependencies      
      - name: Install node.js dependencies
        run: | 
              cd ./ui
              npm install npm -g 
              npm ci --no-optional 
      - name: Set version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Package
        run: ./ci/build.sh
        env:
          SEMVER: ${{ env.RELEASE_VERSION }}
      - name: Build and zip UI-Plugin
        run : |
              cd ./ui
              npm run build-ci
              cd dist/apps/tedge-container-plugin-ui
              zip -r -q ../../../../dist/tedge-container-plugin-ui.zip *
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: dist/*

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          generate_release_notes: true
          draft: true
          files: |
            ./dist/*

      - name: Publish
        if: startsWith(github.ref, 'refs/tags/') && env.PUBLISH_TOKEN
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          PUBLISH_REPO: ${{ secrets.PUBLISH_REPO }}
          PUBLISH_OWNER: ${{ secrets.PUBLISH_OWNER }}
        run: |
          ./ci/publish.sh ./dist --repo "$PUBLISH_REPO" --owner "$PUBLISH_OWNER"
