name: release
on:
  push:
    tags:
      - "*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  release:
    name: Package and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - run: go install github.com/goreleaser/nfpm/v2/cmd/nfpm@latest
        name: Install dependencies

      - name: Set version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - run: mkdir -p dist
      - name: package deb
        run: nfpm package --packager deb --target ./dist/
        env:
          SEMVER: ${{ env.RELEASE_VERSION }}

      - name: package apk
        run: nfpm package --packager apk --target ./dist/
        env:
          SEMVER: ${{ env.RELEASE_VERSION }}

      - name: package rpm
        run: nfpm package --packager rpm --target ./dist/
        env:
          SEMVER: ${{ env.RELEASE_VERSION }}
      
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: dist/*

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          draft: true
          files: |
            ./dist/*
